part1:
	g++ part1.cpp -O0 -o part1O0
	g++ part1.cpp -O1 -o part1O1
	g++ part1.cpp -O2 -o part1O2
	g++ part1.cpp -O3 -o part1O3
part2:
	g++ part2.cpp -O0 -o part2O0
	g++ part2.cpp -O1 -o part2O1
	g++ part2.cpp -O2 -o part2O2
	g++ part2.cpp -O3 -o part2O3
